#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from Nufront Limited
# (C) COPYRIGHT 2011 Nufront Limited
# ALL RIGHTS RESERVED #

# NOTICE
#   This is an autogenerated file, do not edit


LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILT_LIBS := libdec8190vp6.so  libdec8190vp8.so  libdecx170a.so                         libdecx170h.so  libdecx170jpeg.so  libdecx170m2.so                         libdecx170m.so  libdecx170rv.so  libdecx170v.so libdwlx170.so

include $(BUILD_MULTI_PREBUILT)
