#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from Nufront Limited
# (C) COPYRIGHT 2012 Nufront Limited
# ALL RIGHTS RESERVED
#

# NOTICE
#   This is an autogenerated file, do not edit
ifneq ($(MEDIA_VERSION),VER_NS115)

LOCAL_PATH:= $(call my-dir)

#
# libGAL
#
include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := libGAL
LOCAL_PREBUILT_LIBS := libGAL.so

include $(BUILD_MULTI_PREBUILT)

endif
