#
# This confidential and proprietary software may be used only as
# authorised by a licensing agreement from Nufront Limited
# (C) COPYRIGHT 2011 Nufront Limited
# ALL RIGHTS RESERVED
#

# NOTICE
#   This is an autogenerated file, do not edit


LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_PREBUILT_LIBS := libstagefrighthw.so
include $(BUILD_MULTI_PREBUILT)
